//AFFECTS STATE
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const UPDATE_CURRENT_CATEGORY = 'UPDATE_CURRENT_CATEGORY';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_REVIEW = 'ADD_REVIEW';

export const UPDATE_POSTS = 'UPDATE_POSTS';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_MULTIPLE_TO_CART = 'ADD_MULTIPLE_TO_CART';
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const TOGGLE_CART = 'TOGGLE_CART';
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';
export const CLEAR_CART = 'CLEAR_CART';




