export const ADD_TO_CART = 'ADD_TO_CART';
//export const ADD_USER = 'ADD_USER';
//export const LOGIN = 'LOGIN';
//export const ADD_ORDER = 'ADD_ORDER';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_BLUEPRINT = 'ADD_ BLUEPRINT';
export const ADD_CLASS = 'ADD_CLASS';
//export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT_POST = 'ADD_COMMENT_POST';
export const ADD_CLASS_REVIEW = 'ADD_CLASS_REVIEW';
export const ADD_BLUEPRINT_REVIEW = 'ADD_BLUEPRINT_REVIEW';
export const UPDATE_CLASS = 'UPDATE_CLASS';
export const UPDATE_BLUEPRINT = 'UPDATE_BLUEPRINT';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_BLUEPRINT = 'DELETE_BLUEPRINT';
export const DELETE_CLASS = 'DELETE_CLASS';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_COMMENT_POST = 'DELETE_COMMENT_POST';
export const DELETE_BLUEPRINT_REVIEW = 'DELETE_BLUEPRINT_REVIEW';
export const DELETE_CLASS_REVIEW = 'DELETE_CLASS_REVIEW';
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";


// export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
// export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
// export const ADD_TO_CART = "ADD_TO_CART";
// export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
// export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
// export const CLEAR_CART = "CLEAR_CART";
// export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
// export const TOGGLE_CART = "TOGGLE_CART";

